### ISSUE TITLE
Displaying problem of separators

### ISSUE THREAD

**Issue by Grox-Ni** [domtronn/spaceline-all-the-icons.el#64]
- Spacemacs: 0.200.9
- Emacs: 25.3.1 
- OS X: 10.12.3

![screen shot 2017-09-25 at 5 21 02 pm](https://user-images.githubusercontent.com/14857092/30801818-1967659a-a217-11e7-9acb-6ccd857178d9.png)
I put ` (spaceline-all-the-icons-theme)` in user/config. I tried two fonts(Ubuntu Mono/Source Code Pro) but neither improved it. 

Any ideas to solve this?

**Comment by Grox-Ni** [comment]
![screen shot 2017-09-25 at 5 41 03 pm](https://user-images.githubusercontent.com/14857092/30802333-c0cf9180-a218-11e7-92cf-fd31e354cbfb.png)

This is how spaceline displays without all-the-icons

**Comment by idoo** [comment]
sometimes I have same issues 
<img width="204" alt="screen shot 2017-10-12 at 16 02 34" src="https://user-images.githubusercontent.com/738921/31497159-d03a041a-af66-11e7-887d-192ff50b8d01.png">

**Comment by jonbash** [comment]
Also having similar (though more subtle) issues!
![screen shot 2017-11-07 at 09 44 09](https://user-images.githubusercontent.com/8836862/32508782-4604cffc-c3a0-11e7-9909-34ea75cd1a64.png)

**Comment by domtronn** [comment]
@idoo & @jonbash, I'm aware of the alignment issues with the separators unfortunately, problem is the separator characters need to be full height but some whitespace at the bottom of the glyph causes these gaps which then display the background face :/

There's a PR with a new font on [`all-the-icons.el`](https://github.com/domtronn/all-the-icons.el/pull/87) which I'm going to test and _might_ improve things!

**Comment by domtronn** [comment]
@Grox-Ni, it shouldn't be an issue with your main text font as all of the special icons and characters are propertized to use the `all-the-icons` font... I've not been able to reproduce it myself but could you please do the following and tell me what you get?

```el
(describe-face 'mode-line)
```

**Comment by lyr3** [comment]
Same here

ScreenShot: https://i.imgur.com/K73OXnm.png

` (describe-face 'mode-line)`
```

Face: mode-line (sample) (customize this face)

Documentation:
Basic mode line face for selected window.

Defined in `faces.el'.

           Family: unspecified
          Foundry: unspecified
            Width: unspecified
           Height: unspecified
           Weight: unspecified
            Slant: unspecified
       Foreground: #d5c4a1
DistantForeground: unspecified
       Background: #665c54
        Underline: unspecified
         Overline: unspecified
   Strike-through: unspecified
              Box: nil
          Inverse: unspecified
          Stipple: unspecified
             Font: unspecified
          Fontset: unspecified
          Inherit: unspecified

```
